<?php
/** Template Name: Full-day Ridge Walk */
get_header(); ?>
<main id="primary">
<?php ridge_river_intro( 'Walk 02 / Sample itinerary', 'The long ridge.', 'A full day of steady climbing, open horizons and time to settle into the landscape. For walkers who enjoy a sustained day on uneven ground.' ); ?>
<section class="container ridge-detail"><figure><?php ridge_river_photo( '', true ); ?><figcaption>Illustrative stock landscape; this is not a navigable route description.</figcaption></figure><aside class="route-facts"><p class="eyebrow">AT A GLANCE</p><dl><dt>Time outside</dt><dd>Approx. 7 hours</dd><dt>Distance</dt><dd>Approx. 14 km</dd><dt>Ascent</dt><dd>Approx. 750 m</dd><dt>Difficulty</dt><dd>Challenging</dd><dt>Group concept</dt><dd>Up to 6 walkers</dd></dl><a class="button" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Ask about this walk ↗</a><p class="small-note">Sample only. No dates, prices or places are offered for booking.</p></aside></section>
<section class="section container split"><div><p class="eyebrow">THE RHYTHM OF THE DAY</p><h2>One step.<br>Then another.</h2><p>Timings are illustrative and include breaks. Ground conditions, weather and the group’s pace would shape any real itinerary.</p></div><ol class="timeline"><li><span>08:30</span><div><h3>Meet & find our feet</h3><p>Introductions, a kit check and a conversation about the route, pace and turnaround options.</p></div></li><li><span>09:00</span><div><h3>A steady climb</h3><p>Take the ascent in stages, pausing to regroup and watch the view open up.</p></div></li><li><span>12:00</span><div><h3>Lunch with a horizon</h3><p>Find a sheltered place for a packed lunch before following the broad ridge.</p></div></li><li><span>15:30</span><div><h3>Return to the trailhead</h3><p>Descend at a comfortable pace, with time for a final stretch and a look back.</p></div></li></ol></section>
<section class="grade-section section"><div class="container split"><div><h2>What’s part of the idea.</h2><ul class="plain-list"><li>Pre-walk planning conversation and kit notes</li><li>A guided day and regular rest stops</li><li>Route adjustments around conditions and group comfort</li></ul></div><div><h2>What you would bring.</h2><ul class="plain-list"><li>Travel to the agreed meeting point</li><li>Your lunch, water and personal walking kit</li><li>Experience of longer hill walks and sustained ascent</li></ul><p>No accommodation, equipment hire or transport is included in this sample format.</p></div></div></section>
<?php get_template_part( 'template-parts/content', 'cta-banner' ); ?>
</main><?php get_footer(); ?>
