<?php
/** Template Name: Route Field Notes */
get_header(); ?>
<main id="primary">
<?php ridge_river_intro( 'Field notes / Imagined days outside', 'Routes with room to roam.', 'Three sample itineraries to help you picture a day. These are fictional route concepts, not records of completed trips or directions to follow on the ground.' ); ?>
<section class="container field-feature"><?php ridge_river_photo(); ?><div><p class="eyebrow">NOTE 01 / THE HIGH LINE</p><h2>A long ridge.<br>A wide-open day.</h2><p>Climb through the morning, settle into the skyline and leave time for a sheltered lunch. A sustained day for regular hill walkers.</p><a class="button" href="<?php echo esc_url( home_url( '/services/featured/' ) ); ?>">Open the full itinerary ↗</a></div></section>
<section class="section container route-notes"><article><p class="eyebrow">NOTE 02 / THE WATER LINE</p><h2>A riverside ramble.</h2><p>A gentle 6 km loop in the sample plan. Begin on a meadow path, stop for a flask of tea and return along a woodland edge. Allow three hours, including plenty of pauses.</p><dl><dt>Look out for</dt><dd>Changing light on the water and the quiet between footfalls.</dd><dt>Plan around</dt><dd>Wet ground, seasonal path closures and considerate use of shared trails.</dd></dl><a class="text-link" href="<?php echo esc_url( home_url( '/services/#day-walks' ) ); ?>">Explore day walks ↗</a></article><article><p class="eyebrow">NOTE 03 / THE LEARNING LINE</p><h2>Finding a bearing.</h2><p>A 5 km teaching loop in the sample plan. Match the contours to the hillside, identify useful landmarks and practise a simple bearing in an unhurried four-hour session.</p><dl><dt>Look out for</dt><dd>The small features that turn a paper map into a recognisable place.</dd><dt>Plan around</dt><dd>Good visibility, a suitable practice area and time for questions.</dd></dl><a class="text-link" href="<?php echo esc_url( home_url( '/services/#navigation' ) ); ?>">Explore navigation walks ↗</a></article></section>
<?php get_template_part( 'template-parts/content', 'single-service-highlight' ); ?>
</main><?php get_footer(); ?>
