<?php
/** Template Name: Walking Journal */
get_header(); ?>
<main id="primary">
<?php ridge_river_intro( 'The journal / Notes for the way', 'A little preparation. A better day.', 'Packing, planning and sharing the trail. Short reads for a more thoughtful day outdoors.' ); ?>
<section class="container journal-index"><a href="#packing"><span>01</span> Pack with purpose ↓</a><a href="#weather"><span>02</span> Leave room for weather ↓</a><a href="#etiquette"><span>03</span> Share the path ↓</a></section>
<section class="section container journal-entries">
<article id="packing"><div><p class="eyebrow">01 / PACKING · 3 MIN READ</p><h2>Pack with purpose.</h2><?php ridge_river_mark( 1 ); ?></div><div class="prose"><p>A comfortable pack starts with the day you actually have in mind. Think about the length of the walk, the ground underfoot and the time you might spend standing still.</p><h3>Keep the useful things close</h3><p>Water, a snack and a waterproof layer belong somewhere easy to reach. Put spare clothing in a dry bag, and leave enough room to stow the layer you take off during a climb.</p><h3>Remember the pauses</h3><p>A warm layer earns its place when the pace slows or lunch runs long. Bring personal essentials and footwear you already know, rather than discovering a new pair of boots halfway around a route.</p><p>This short list is a starting point, not a complete kit prescription. The final list should reflect the route, season and individual needs.</p><a class="text-link" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Talk through a sample day ↗</a></div></article>
<article id="weather"><div><p class="eyebrow">02 / PLANNING · 3 MIN READ</p><h2>Leave room<br>for weather.</h2><?php ridge_river_mark( 2 ); ?></div><div class="prose"><p>A forecast helps shape a plan; it doesn’t promise the shape of the day. Look beyond the headline temperature and think about wind, visibility, rainfall and the hours of daylight available.</p><h3>Have another good day in mind</h3><p>A sheltered woodland route can be just as rewarding as a ridge. Make an alternative part of the plan from the beginning, so choosing it feels like good judgement rather than a disappointment.</p><h3>Agree the decisions early</h3><p>Before setting off, discuss when to review conditions and when to turn around. On a real outing, consult relevant local forecasts, access information and current ground conditions.</p><p>Our sample itineraries contain no live weather or route-status information.</p><a class="text-link" href="<?php echo esc_url( home_url( '/services/featured/' ) ); ?>">Read the sample ridge plan ↗</a></div></article>
<article id="etiquette"><div><p class="eyebrow">03 / TRAIL ETIQUETTE · 2 MIN READ</p><h2>Share the path.</h2><?php ridge_river_mark( 3 ); ?></div><div class="prose"><p>The outdoors is home, habitat and workplace as well as somewhere to walk. A thoughtful day leaves room for everyone who belongs there.</p><h3>Notice who is around you</h3><p>Give other path users space, keep noise considerate and follow signs and local access guidance. Leave gates as instructed and avoid disturbing livestock or wildlife.</p><h3>Carry the small things home</h3><p>Take all litter away, including food scraps. Stay on established routes where appropriate, resist shortcuts that widen erosion and leave plants and stones where you found them.</p><p>Good trail manners are rarely dramatic. They are the small choices that let the next person enjoy the same quiet view.</p><a class="text-link" href="<?php echo esc_url( home_url( '/about/' ) ); ?>">Our walking ethos ↗</a></div></article>
</section>
<?php get_template_part( 'template-parts/content', 'blog-preview' ); ?>
</main><?php get_footer(); ?>
