<?php
/** Template Name: Blue Hour — Private Listening Event */
get_header(); ?>
<main id="primary">
<?php blue_hour_intro( 'Private listening events', 'A room for your kind of occasion.', 'A milestone dinner, a thoughtful gathering, or an evening that needs no excuse. Imagine bringing your people into the Blue Hour mood.' ); ?>
<section class="container archive-feature"><figure><?php blue_hour_photo( 'detail', '', true ); ?><figcaption>Illustrative instrument photograph / not a venue photograph</figcaption></figure><div><p class="eyebrow">One evening, thoughtfully paced</p><h2>Start with the feeling.</h2><p>A private listening event pairs a relaxed welcome with music given its own moment. A hosted vinyl selection can keep things intimate; a small acoustic duo can bring a little spontaneity.</p><p>The imagined flow: arrive, settle, listen, pause, and let the conversation return. Music shapes the evening without filling every second.</p><?php blue_hour_link( '/contact/', 'Try a sample event inquiry ↗', 'button' ); ?></div></section>
<section class="section container"><div class="section-heading"><h2>A few possible arrangements.</h2><p>All capacities and durations below are illustrative.<br>No actual venue limits or availability are implied.</p></div><div class="arrangement-grid"><article><p class="eyebrow">01 / The record room</p><h3>12–20 listeners</h3><p>A seated, hosted record evening with two complete album sides and a break for conversation. Example duration: two hours.</p></article><article><p class="eyebrow">02 / The close-up set</p><h3>20–30 listeners</h3><p>A small acoustic duo, two focused sets, and an unhurried interval. Example duration: two and a half hours.</p></article><article><p class="eyebrow">03 / The whole evening</p><h3>30–40 guests</h3><p>A relaxed gathering with a dedicated seated listening moment. Example duration: three hours. Layout would need venue confirmation.</p></article></div></section>
<section class="section container event-process"><div><?php blue_hour_photo( 'hero' ); ?></div><div><p class="eyebrow">From a thought to an evening</p><h2>Give the night a shape.</h2><ol><li><strong>Share the occasion.</strong> Set a mood, a group size, and a preferred date.</li><li><strong>Choose the sound.</strong> Imagine a live duo or a hosted record selection.</li><li><strong>Consider the room.</strong> Confirm access, seating, hospitality, and timing with a real operator before any booking.</li></ol><details><summary>Are prices or catering included?</summary><p>No packages, prices, catering commitments, or real bookings are offered by this sample. These arrangements illustrate possibilities only.</p></details><?php blue_hour_link( '/contact/', 'Open the sample booking notebook ↗', 'text-link' ); ?></div></section>
</main><?php get_footer(); ?>
