<?php
/** Template Name: Blue Hour — Listening Journal */
get_header(); ?>
<main id="primary">
<?php blue_hour_intro( 'Journal', 'Notes for open ears.', 'A short reading shelf for the curious listener. No homework required, and no right way to hear a piece of music.' ); ?>
<section class="container journal-index"><p class="eyebrow">In this edition</p><a href="#follow-the-bass">01 / Follow the bass ↘</a><a href="#space-between">02 / The space between notes ↘</a><a href="#first-set">03 / Your first live set ↘</a></section>
<div class="container journal-layout"><aside><?php blue_hour_photo( 'hero', '', true ); ?><p class="caption">A small detail. A whole world of sound.</p></aside><div>
<article class="journal-entry" id="follow-the-bass"><p class="eyebrow">01 / A listening introduction · 2 min</p><h2>Start at the bottom. Follow the bass.</h2><p>When the tune feels busy, listen for the lowest moving line. The bass often gives you a way through: a pulse to walk beside, a repeating shape, or a small nudge into a new harmony.</p><p>Try keeping your attention there for one chorus. Then move to the piano or voice. The same passage can feel completely different when you choose another thread to follow.</p><p>You do not need to name the chords. Notice where the music feels settled, and where it seems to lean forward. That small change in attention can open the whole piece.</p></article>
<article class="journal-entry" id="space-between"><p class="eyebrow">02 / Listening practice · 2 min</p><h2>The space between the notes.</h2><p>A pause is part of the phrase. It lets a sound decay, gives another player room to answer, and makes the next entrance feel earned. In a quiet room, the tail of a piano note can become its own small event.</p><p>On your next listen, pay attention to where a musician stops. What carries on underneath? Does the silence relax the music or create a little suspense?</p><p>This is one reason Blue Hour imagines a listening-first room. Soft sounds deserve somewhere to land.</p></article>
<article class="journal-entry" id="first-set"><p class="eyebrow">03 / Room etiquette · 2 min</p><h2>Your first set, without the nerves.</h2><p>Settle in before the music starts and silence your phone. If you need to step out, a break between pieces is a considerate moment. Save long conversations for the interval.</p><p>Applause often follows a solo, and always fits at the end of a piece. If you are unsure, let the room guide you. You are there to enjoy the exchange, not to pass a test.</p><p>Most of all, allow yourself to be surprised. A tune you thought was not for you might become the one you remember on the way home.</p></article>
</div></div>
<section class="container journal-outro"><?php blue_hour_link( '/services/', 'Find your next kind of evening ↗', 'button' ); ?></section>
</main><?php get_footer(); ?>
