<?php /** Template Name: Journal */ get_header(); ?>
<main id="primary" tabindex="-1">
<?php ff_intro( 'Journal / Observations from the studio', 'Looking a little closer.', 'Notes on the small decisions that change how a place feels. A reading room for ideas about light, scale and the life of existing buildings.' ); ?>
<div class="container journal-layout"><aside class="journal-index"><p class="eyebrow">In this issue</p><a href="#light">01 / Following the light</a><a href="#scale">02 / The scale of everyday life</a><a href="#reuse">03 / Before you begin again</a><?php ff_image( 'detail' ); ?><p class="small">Illustrative photograph by Annie Spratt.</p></aside><div class="journal-articles">
<article id="light"><p class="eyebrow">01 / Light · A field note</p><h2>Following the light.</h2><p class="lead">Before deciding where a room should be, spend a day noticing the light that is already there.</p><p>Morning light has a different character from afternoon sun. A kitchen used early may benefit from a different orientation than a room for evening reading. Draw a simple plan and mark where the sun reaches at three moments during the day.</p><p>Notice the light reflected from neighbouring walls as well as direct sunlight. A pale surface can brighten a deep room; a deep reveal can soften glare. The largest window is not always the most comfortable one.</p><h3>Try this at home</h3><p>Photograph the same corner in the morning, at midday and in the evening. Note when it feels most inviting, where glare appears and whether you instinctively move a chair. Those observations make a useful design brief.</p></article>
<article id="scale"><p class="eyebrow">02 / Scale · A field note</p><h2>The scale of everyday life.</h2><p class="lead">A room is experienced through movement, reach and the things we choose to keep close.</p><p>A plan can look generous while feeling awkward in use. Begin with a familiar routine: arriving with bags, setting a table or opening a wardrobe. Trace the movement and the space each action needs.</p><p>Furniture is a useful measuring tool. Rather than imagining an empty room, test it with the actual table, chair or bed you intend to use. Leave room for doors, circulation and people sitting together.</p><h3>Make the drawing physical</h3><p>Mark a proposed piece of joinery on the floor with removable tape. Walk around it. The difference between a line on paper and an edge you move past is often the most useful part of the exercise.</p></article>
<article id="reuse"><p class="eyebrow">03 / Reuse · A field note</p><h2>Before you begin again.</h2><p class="lead">An existing building is a collection of decisions, materials and possibilities. Read it before rewriting it.</p><p>Start with an inventory. Record the doors that still work well, the floor that can be repaired and the wall whose texture gives the room character. Distinguish wear from failure; they ask for different responses.</p><p>Changing how a room is used can sometimes achieve more than changing its structure. Test small adjustments first: a new opening between uses, better storage or a revised lighting arrangement.</p><h3>Know when to ask</h3><p>Structural changes, moisture problems and unfamiliar materials need qualified assessment. A careful survey helps turn affection for an old building into a realistic plan for its next chapter.</p></article>
</div></div>
<?php get_template_part( 'template-parts/content', 'cta-banner' ); ?>
</main><?php get_footer(); ?>
