<?php $services = nolan_young_template_services(); $plans = nolan_young_template_plans(); $articles = nolan_young_template_articles(); ?>
<div class="footer-widgets">
	<section class="footer-brand"><a class="site-branding" href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php nolan_young_template_render_logo(); ?></a><p><?php esc_html_e( 'Evergreen Yardworks provides reliable lawn care, thoughtful landscape maintenance, and seasonal property cleanup for homes that need to look cared for all year.', '005-nolan-young-theme-evergreen-yardworks' ); ?></p><a class="btn btn-secondary btn-small" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>"><?php esc_html_e( 'Schedule a Cleanup', '005-nolan-young-theme-evergreen-yardworks' ); ?></a></section>
	<nav aria-label="<?php esc_attr_e( 'Footer services', '005-nolan-young-theme-evergreen-yardworks' ); ?>"><h2><?php esc_html_e( 'Services', '005-nolan-young-theme-evergreen-yardworks' ); ?></h2><?php foreach ( array_slice( $services, 0, 8 ) as $service ) : ?><a href="<?php echo esc_url( $service['url'] ); ?>"><?php echo esc_html( $service['title'] ); ?></a><?php endforeach; ?></nav>
	<nav aria-label="<?php esc_attr_e( 'Footer plans', '005-nolan-young-theme-evergreen-yardworks' ); ?>"><h2><?php esc_html_e( 'Plans', '005-nolan-young-theme-evergreen-yardworks' ); ?></h2><?php foreach ( $plans as $plan ) : ?><a href="<?php echo esc_url( home_url( '/services/' ) ); ?>"><?php echo esc_html( $plan['title'] ); ?></a><?php endforeach; ?></nav>
	<nav aria-label="<?php esc_attr_e( 'Footer seasonal guide', '005-nolan-young-theme-evergreen-yardworks' ); ?>"><h2><?php esc_html_e( 'Seasonal Guide', '005-nolan-young-theme-evergreen-yardworks' ); ?></h2><?php foreach ( array_slice( $articles, 0, 5 ) as $article ) : ?><a href="<?php echo esc_url( $article['url'] ); ?>"><?php echo esc_html( $article['title'] ); ?></a><?php endforeach; ?></nav>
	<section class="footer-contact"><h2><?php esc_html_e( 'Contact', '005-nolan-young-theme-evergreen-yardworks' ); ?></h2><p><?php esc_html_e( 'Serving residential properties, small HOAs, rentals, and light commercial grounds across the metro area.', '005-nolan-young-theme-evergreen-yardworks' ); ?></p><a href="tel:+15550147826">(555) 014-7826</a><a href="mailto:hello@evergreenyardworks.example">hello@evergreenyardworks.example</a><p><?php esc_html_e( 'Office replies Monday-Friday; crew schedules vary by season and weather.', '005-nolan-young-theme-evergreen-yardworks' ); ?></p></section>
</div>

