<?php
/** Template Name: Intro to Handbuilding */
get_header();
?>
<main id="primary">
	<?php clay_page_intro( 'Intro to handbuilding', 'An afternoon in good hands.', 'A gentle first encounter with clay. Learn to pinch, coil and shape a small vessel, with plenty of room to find your own rhythm.' ); ?>
	<section class="container workshop-detail"><figure><?php clay_image( 'hero', '', true ); ?><figcaption>Illustrative ceramic forms; workshop results will vary.</figcaption></figure><div class="workshop-facts"><p class="eyebrow">At a glance</p><dl class="spec-list"><div><dt>Duration</dt><dd>2½ hours</dd></div><div><dt>Experience</dt><dd>Complete beginners welcome</dd></div><div><dt>Included in the concept</dt><dd>Clay, shared tools, an apron and guided practice</dd></div><div><dt>Booking</dt><dd>Demonstration only — no dates, prices or places are offered</dd></div></dl><a class="button" href="#workshop-inquiry">Ask about the workshop ↗</a></div></section>
	<section class="section container split"><div><p class="eyebrow">The afternoon, slowly</p><h2>From a handful of clay<br><em>to a form of your own.</em></h2></div><ol class="process-list"><li><span>01</span><div><h3>Settle in · 20 minutes</h3><p>Meet the material, prepare the table and practise a few simple movements.</p></div></li><li><span>02</span><div><h3>Find a form · 90 minutes</h3><p>Make a pinch pot or small coiled vessel. Explore balance, wall thickness and a comfortable rim.</p></div></li><li><span>03</span><div><h3>Refine &amp; reflect · 40 minutes</h3><p>Add texture, tidy joins and talk through drying, glazing and firing.</p></div></li></ol></section>
	<section class="container faq-section section"><div><h2>Before you<br><em>roll up your sleeves.</em></h2></div><div class="faq-list"><details><summary>What should I bring?</summary><p>Wear comfortable clothes that can get dusty, tie back long hair and keep jewellery away from the clay. All making materials are part of the sample workshop concept.</p></details><details><summary>Do I take my piece home that day?</summary><p>Wet clay needs to dry before it can be fired. A real booking would confirm firing, glazing, collection arrangements and any fees in advance. This demo does not promise a finished piece or collection date.</p></details><details><summary>Can I come with a friend?</summary><p>The concept is well suited to making together. Group size and access needs would be discussed before booking; there are no live places to reserve here.</p></details></div></section>
	<section class="section container narrow" id="workshop-inquiry"><p class="eyebrow">A first conversation</p><h2>Make a little room<br><em>for making.</em></h2><?php clay_inquiry_form( true ); ?><a class="text-link" href="<?php echo clay_url( '/services/' ); ?>">← All studio experiences</a></section>
</main>
<?php get_footer(); ?>
