<?php
/** Template Name: The Collection */
get_header();
?>
<main id="primary">
	<?php clay_page_intro( 'The collection', 'Small forms. A lasting presence.', 'An illustrative vessel collection: two studies in surface, proportion and the objects we choose to keep close. These are visual references, not products for sale.' ); ?>
	<section id="chalk" class="section container collection-entry"><figure class="white-vessels"><?php clay_image( 'hero', '', true ); ?><figcaption>White ceramic vessels · Tom Crew / Unsplash</figcaption></figure><div><p class="eyebrow">01 / Chalk — illustrative study</p><h2>The everyday<br><em>vessel.</em></h2><p>A family of pale cylinders with a soft, irregular lip. Seen together, their different heights create a quiet rhythm; alone, each form holds its own.</p><dl class="spec-list"><div><dt>Material direction</dt><dd>Stoneware with a pale, speckled glaze; an imagined material brief, not a verified specification of the photographed objects.</dd></div><div><dt>Intended setting</dt><dd>A shelf, a side table, or a study in repeated forms.</dd></div><div><dt>Care approach</dt><dd>Gentle hand washing and a dry base. Confirm water resistance and food suitability with the actual maker.</dd></div></dl><a class="text-link" href="<?php echo clay_url( '/contact/' ); ?>">Discuss a form of your own ↗</a></div></section>
	<section id="ember" class="section container collection-entry reverse"><figure class="red-vessel"><?php clay_image( 'detail' ); ?><figcaption>Red ceramic vase · 五玄土 ORIENTO / Unsplash</figcaption></figure><div><p class="eyebrow">02 / Ember — illustrative study</p><h2>A place for<br><em>one stem.</em></h2><p>A slender neck and a warm, mottled surface. This colour study explores how one strong note can bring warmth to a quiet room.</p><dl class="spec-list"><div><dt>Material direction</dt><dd>Ceramic body with an iron-red surface direction. The photograph is a reference, not a studio glaze sample.</dd></div><div><dt>Intended setting</dt><dd>A single dried stem, a narrow ledge, a small moment of colour.</dd></div><div><dt>Care approach</dt><dd>Dust with a soft cloth. Protect the surface underneath and avoid abrupt temperature changes.</dd></div></dl><a class="text-link" href="<?php echo clay_url( '/blog/#care' ); ?>">Read our care notes ↗</a></div></section>
	<aside class="container collection-note"><p>No checkout, stock claims or prices: Clay &amp; Still is a fictional studio. Both photographs are credited visual references, not work made by this brand.</p></aside>
	<?php get_template_part( 'template-parts/content', 'single-service-highlight' ); ?>
</main>
<?php get_footer(); ?>
