'use strict';
const {fs,path,crypto,ROOT,ensureDir,writeJson,readJson,ensureInside,relative,titleFromSlug,assertStatus,normalizeRelativeFile}=require('./workspace');
const {spawnSync}=require('node:child_process');
const SEEDED_ASSET_MANIFEST='assets/images/asset-manifest.json';
const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
function prepareGeneratedAssets(themeDir, options = {}) {
  const themeSlug = path.basename(themeDir);
  const brand = titleFromSlug(themeSlug).replace(/^\d{3}\s+Nolan Young Theme\s+/, '');
  const catalog = options.assetCatalog ? readApprovedAssetCatalog(options.assetCatalog) : seededAssetCatalog(themeSlug, brand);
  validateAssetCatalog(catalog);
  const isLandscaping = isLandscapingTheme(themeSlug);
  const acquiredAt = new Date().toISOString();

  const paletteSeed = themeSlug.replace(/^\d{3}_nolan_young_theme_/, '');
  const palette = isLandscaping ? landscapingPalette() : paletteForSlug(paletteSeed);

  for (const asset of catalog) {
    const target = path.join(themeDir, asset.path);
    ensureDir(path.dirname(target));
    if (asset.kind === 'stock-photo') {
      if (options.assetCatalog) {
        const cached = path.join(ROOT, 'assets', 'approved-stock', `${crypto.createHash('sha256').update(asset.sourceUrl).digest('hex')}.jpg`);
        ensureDir(path.dirname(cached));
        downloadStockPhoto(asset.sourceUrl, cached);
        fs.copyFileSync(cached, target);
      } else {
        downloadStockPhoto(asset.sourceUrl, target);
      }
    } else {
      fs.writeFileSync(target, isLandscaping ? createLandscapingIconSvg(asset.role, palette) : createIconSvg(asset.role, palette));
    }
  }

  const assets = catalog.map((asset, index) => normalizePreparedAsset(asset, themeSlug, acquiredAt, index));
  const manifest = {
    generatedAt: acquiredAt,
    themeSlug,
    source: 'Deterministic provider-neutral asset preparation by the Nolan Young Theme Factory before AI generation.',
    license: 'Stock photos are downloaded from Unsplash and governed by the Unsplash License: free commercial and non-commercial use, no permission required, attribution appreciated. Local SVG icons are original generated interface assets for this theme run.',
    usageRule: 'Every generation provider receives this same approved asset set. Stock photos are for photographic/hero/portfolio/menu imagery; SVG is for interface marks, icons, and small UI details.',
    assets
  };
  writeJson(path.join(themeDir, SEEDED_ASSET_MANIFEST), manifest);
}

function readApprovedAssetCatalog(catalogPath) {
  const file = path.resolve(ROOT, catalogPath);
  ensureInside(path.join(ROOT, 'assets', 'manifests'), file);
  const catalog = readJson(file);
  if (catalog.approved !== true || !Array.isArray(catalog.assets) || !catalog.assets.length) {
    throw new Error('Asset catalog must contain a reviewed, approved asset list.');
  }
  const seen = new Set();
  for (const asset of catalog.assets) {
    if (!/^assets\/(images|icons)\/[a-z0-9_/-]+\.(jpg|svg)$/.test(asset.path || '') || asset.path.includes('..') || seen.has(asset.path)) {
      throw new Error(`Invalid or duplicate asset catalog path: ${asset.path}`);
    }
    if (!['stock-photo', 'local-svg-icon'].includes(asset.kind)) throw new Error(`Unsupported approved asset kind: ${asset.kind}`);
    if (asset.kind === 'stock-photo' && !asset.path.endsWith('.jpg')) throw new Error('Stock photos must use a .jpg destination.');
    if (asset.kind === 'local-svg-icon' && !asset.path.endsWith('.svg')) throw new Error('Local icons must use an .svg destination.');
    seen.add(asset.path);
  }
  validateAssetCatalog(catalog.assets);
  return catalog.assets;
}

function normalizePreparedAsset(asset, themeSlug, acquiredAt, index) {
  const stock = asset.kind === 'stock-photo';
  const baseName = path.basename(asset.path, path.extname(asset.path)).replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  return {
    ...asset,
    id: `${String(index + 1).padStart(2, '0')}-${baseName}`,
    file: asset.path,
    source: stock ? 'Unsplash' : 'Original local asset generated by the Nolan Young Theme Factory',
    source_url: stock ? asset.pageUrl : 'https://github.com/nolanyoungg/Nolan-Young-Theme-Factory',
    license: stock ? 'Unsplash License' : 'Project-owned original asset distributed with the theme',
    license_url: stock ? 'https://unsplash.com/license' : 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.html',
    creator: stock ? asset.creator : 'Nolan Young Theme Factory',
    creator_url: stock ? asset.creatorUrl : 'https://shibey.com',
    acquired_at: acquiredAt,
    allowed_use: 'Approved for this static sample and optional WordPress conversion.',
    theme_slug: themeSlug,
    alt_text: asset.alt,
    notes: asset.role
  };
}

function validateAssetCatalog(catalog) {
  for (const asset of catalog) {
    if (asset.kind !== 'stock-photo') {
      continue;
    }
    const canonicalPage = typeof asset.pageUrl === 'string'
      && /^https:\/\/unsplash\.com\/photos\/(?!photo-)[^/?#]+(?:[?#].*)?$/.test(asset.pageUrl);
    const complete = typeof asset.sourceUrl === 'string'
      && asset.sourceUrl.startsWith('https://images.unsplash.com/')
      && canonicalPage
      && typeof asset.creator === 'string'
      && asset.creator.trim()
      && typeof asset.creatorUrl === 'string'
      && /^https:\/\/unsplash\.com\/@[^/?#]+\/?$/.test(asset.creatorUrl);
    if (!complete) {
      throw new Error(`Approved stock asset "${asset.path}" is missing verified creator or canonical Unsplash source metadata.`);
    }
  }
}

function requirePreparedAssetManifest(themeDir) {
  const manifestPath = path.join(themeDir, SEEDED_ASSET_MANIFEST);
  if (!fs.existsSync(manifestPath)) {
    throw new Error('Missing approved asset manifest for theme generation.');
  }
  return manifestPath;
}

function recordAssetPreparation(themeDir, reportDir, options = {}) {
  const manifestPath = requirePreparedAssetManifest(themeDir);
  const manifest = readJson(manifestPath);
  const evidence = {
    status: 'prepared',
    themeSlug: path.basename(themeDir),
    prompt: options.promptPath ? relative(options.promptPath) : null,
    manifest: relative(manifestPath),
    manifestHash: sha256File(manifestPath),
    approvedAssetSetHash: hashApprovedAssetSet(themeDir, manifest),
    assetCount: Array.isArray(manifest.assets) ? manifest.assets.length : 0,
    recordedAt: new Date().toISOString()
  };
  writeJson(path.join(reportDir, 'asset-preparation.json'), evidence);
  return evidence;
}

function hashApprovedAssetSet(themeDir, manifest) {
  const hash = crypto.createHash('sha256');
  const assets = Array.isArray(manifest.assets) ? [...manifest.assets] : [];
  assets.sort((left, right) => String(left.path || left.file).localeCompare(String(right.path || right.file), 'en'));
  for (const asset of assets) {
    const relPath = normalizeRelativeFile(asset.path || asset.file);
    const assetPath = path.join(themeDir, ...relPath.split('/'));
    ensureInside(themeDir, assetPath);
    if (!fs.existsSync(assetPath) || !fs.statSync(assetPath).isFile()) {
      throw new Error(`Approved asset is missing: ${relPath}`);
    }
    hash.update(relPath);
    hash.update(Buffer.from([0]));
    hash.update(fs.readFileSync(assetPath));
    hash.update(Buffer.from([0]));
  }
  return hash.digest('hex');
}

function sha256File(file) {
  return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

function seededAssetCatalog(themeSlug, brand) {
  if (isLandscapingTheme(themeSlug)) {
    return landscapingStockAssets(brand);
  }
  return softwareAgencyStockAssets(brand);
}

function isLandscapingTheme(themeSlug) {
  return /(lawn|landscap|garden|yard|grounds|turf)/i.test(themeSlug);
}

function landscapingStockAssets(brand) {
  return [
    {
      path: 'assets/images/hero/curb-appeal-lawn.jpg',
      kind: 'stock-photo',
      role: 'homepage hero photo for a professionally maintained residential lawn and landscape',
      alt: `${brand} freshly maintained residential lawn and planting beds`,
      sourceUrl: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=1800&q=82',
      pageUrl: 'https://unsplash.com/photos/photo-1558904541-efa843a96f01'
    },
    {
      path: 'assets/images/hero/garden-crew-hands.jpg',
      kind: 'stock-photo',
      role: 'header dropdown and process photo for hands-on planting and garden care',
      alt: `${brand} landscape crew hands planting and improving garden beds`,
      sourceUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1600&q=82',
      pageUrl: 'https://unsplash.com/photos/photo-1416879595882-3373a0480b5b'
    },
    {
      path: 'assets/images/portfolio/landscape-install.jpg',
      kind: 'stock-photo',
      role: 'portfolio photo for landscape installation, lawn renovation, and outdoor living upgrades',
      alt: `${brand} landscape installation with healthy planting and outdoor detail`,
      sourceUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1600&q=82',
      pageUrl: 'https://unsplash.com/photos/photo-1625246333195-78d9c38ad449'
    },
    {
      path: 'assets/images/portfolio/lawn-maintenance.jpg',
      kind: 'stock-photo',
      role: 'services photo for recurring mowing, edging, trimming, and seasonal lawn maintenance',
      alt: `${brand} lawn maintenance crew work and fresh turf detail`,
      sourceUrl: 'https://images.unsplash.com/photo-1598902108854-10e335adac99?auto=format&fit=crop&w=1600&q=82',
      pageUrl: 'https://unsplash.com/photos/photo-1598902108854-10e335adac99'
    },
    {
      path: 'assets/images/portfolio/seasonal-planting.jpg',
      kind: 'stock-photo',
      role: 'seasonal color, garden bed refresh, mulching, pruning, and planting services photo',
      alt: `${brand} seasonal planting and garden bed care`,
      sourceUrl: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=1600&q=82',
      pageUrl: 'https://unsplash.com/photos/photo-1591857177580-dc82b9ac4e1e'
    },
    {
      path: 'assets/images/texture/meadow-texture.jpg',
      kind: 'stock-photo',
      role: 'subtle grass and meadow texture photo for background crops and service bands',
      alt: '',
      sourceUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80',
      pageUrl: 'https://unsplash.com/photos/photo-1500382017468-9049fed747ef'
    },
    {
      path: 'assets/icons/platform-mark.svg',
      kind: 'local-svg-icon',
      role: 'original local leaf, path, and service-route interface mark',
      alt: `${brand} leaf and landscape route mark`
    },
    {
      path: 'assets/icons/icon1.svg',
      kind: 'local-svg-icon',
      role: 'original local fallback icon matching this landscaping brand',
      alt: `${brand} fallback service mark`
    }
  ];
}

function softwareAgencyStockAssets(brand) {
  return [
    {
      path: 'assets/images/hero/agency-workspace.jpg',
      kind: 'stock-photo',
      role: 'homepage hero photo showing a contemporary office interior',
      alt: 'Office hallway with glass-panel doors and adjacent work areas',
      sourceUrl: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=82',
      pageUrl: 'https://unsplash.com/photos/hallway-between-glass-panel-doors-yWwob8kwOCk',
      creator: 'Nastuh Abootalebi',
      creatorUrl: 'https://unsplash.com/@sunday_digital'
    },
    {
      path: 'assets/images/hero/developer-screens.jpg',
      kind: 'stock-photo',
      role: 'header dropdown and services photo for software development screens',
      alt: 'MacBook displaying code on a busy desk',
      sourceUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1600&q=82',
      pageUrl: 'https://unsplash.com/photos/a-macbook-with-lines-of-code-on-its-screen-on-a-busy-desk-m_HRfLhgABo',
      creator: 'Christopher Gower',
      creatorUrl: 'https://unsplash.com/@cgower'
    },
    {
      path: 'assets/images/portfolio/ecommerce-planning.jpg',
      kind: 'stock-photo',
      role: 'Shopify and ecommerce planning case-study photo',
      alt: 'Laptop displaying analytics on a glass-top table',
      sourceUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1600&q=82',
      pageUrl: 'https://unsplash.com/photos/laptop-computer-on-glass-top-table-hpjSkU2UYSU',
      creator: 'Carlos Muza',
      creatorUrl: 'https://unsplash.com/@kmuza'
    },
    {
      path: 'assets/images/portfolio/team-collaboration.jpg',
      kind: 'stock-photo',
      role: 'about and process photo for collaborative agency work',
      alt: 'People collaborating around a table with laptops',
      sourceUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=82',
      pageUrl: 'https://unsplash.com/photos/HkTMcmlMOUQ',
      creator: 'Annie Spratt',
      creatorUrl: 'https://unsplash.com/@anniespratt'
    },
    {
      path: 'assets/images/portfolio/performance-review.jpg',
      kind: 'stock-photo',
      role: 'WordPress performance and analytics case-study photo',
      alt: 'Laptop screen displaying performance analytics graphs',
      sourceUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1600&q=82',
      pageUrl: 'https://unsplash.com/photos/graphs-of-performance-analytics-on-a-laptop-screen-JKUTrJ4vK00',
      creator: 'Luke Chesser',
      creatorUrl: 'https://unsplash.com/@lukechesser'
    },
    {
      path: 'assets/images/texture/studio-detail.jpg',
      kind: 'stock-photo',
      role: 'subtle editorial texture photo for background crops',
      alt: '',
      sourceUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1600&q=80',
      pageUrl: 'https://unsplash.com/photos/FlPc9_VocJ4',
      creator: 'John Schnobrich',
      creatorUrl: 'https://unsplash.com/@johnishappysometimes'
    },
    {
      path: 'assets/icons/platform-mark.svg',
      kind: 'local-svg-icon',
      role: 'original local brand/interface mark',
      alt: `${brand} platform mark`
    },
    {
      path: 'assets/icons/icon1.svg',
      kind: 'local-svg-icon',
      role: 'original local fallback icon matching this run brand',
      alt: `${brand} fallback mark`
    }
  ];
}

function downloadStockPhoto(sourceUrl, target) {
  if (fs.existsSync(target) && fs.statSync(target).size > 1024) {
    return;
  }
  const result = spawnSync(process.execPath, ['-e', `
    const fs = require('node:fs');
    (async () => {
      const response = await fetch(process.argv[1], { signal: AbortSignal.timeout(120000) });
      if (!response.ok) throw new Error('Image download returned HTTP ' + response.status);
      if (!/^image\\//i.test(response.headers.get('content-type') || '')) throw new Error('Image download did not return an image');
      const bytes = Buffer.from(await response.arrayBuffer());
      if (bytes.length < 1024) throw new Error('Image download is unexpectedly small');
      fs.writeFileSync(process.argv[2], bytes);
    })().catch((error) => { console.error(error.message); process.exitCode = 1; });
  `, sourceUrl, target], {
    cwd: ROOT,
    encoding: 'utf8',
    maxBuffer: 1024 * 1024 * 20
  });
  assertStatus(result, `download stock photo ${sourceUrl}`);
  if (!fs.existsSync(target) || fs.statSync(target).size < 1024) {
    throw new Error(`Downloaded stock photo is unexpectedly small: ${relative(target)}`);
  }
}

function readSeededAssetInventory(themeDir) {
  const manifestPath = path.join(themeDir, SEEDED_ASSET_MANIFEST);
  if (!fs.existsSync(manifestPath)) {
    return '';
  }
  const manifest = readJson(manifestPath);
  return [
    `Manifest: ${SEEDED_ASSET_MANIFEST}`,
    ...manifest.assets.map((asset) => `- ${asset.path} (${asset.kind}): ${asset.role}; alt="${asset.alt}"`)
  ].join('\n');
}

function paletteForSlug(slug) {
  const seed = [...slug].reduce((sum, char) => sum + char.charCodeAt(0), 0);
  const hue = seed % 360;
  return {
    dark: hsl(hue, 42, 10),
    mid: hsl((hue + 38) % 360, 72, 36),
    bright: hsl((hue + 92) % 360, 88, 58),
    accent: hsl((hue + 168) % 360, 80, 62),
    pale: hsl((hue + 210) % 360, 82, 86)
  };
}

function landscapingPalette() {
  return {
    dark: '#14251b',
    mid: '#2f6b3f',
    bright: '#6f8f3d',
    accent: '#d99a2b',
    pale: '#eef6e8'
  };
}

function hsl(h, s, l) {
  return `hsl(${h} ${s}% ${l}%)`;
}

function createIconSvg(label, palette) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96" role="img" aria-label="${escapeHtml(label)}">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="${palette.dark}"/>
      <stop offset=".52" stop-color="${palette.mid}"/>
      <stop offset="1" stop-color="${palette.bright}"/>
    </linearGradient>
  </defs>
  <rect width="96" height="96" rx="24" fill="url(#g)"/>
  <path d="M24 56 42 28l12 19 9-13 13 22" fill="none" stroke="white" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>
  <circle cx="32" cy="30" r="7" fill="${palette.accent}"/>
  <path d="M21 70h54" stroke="rgba(255,255,255,.72)" stroke-width="6" stroke-linecap="round"/>
</svg>
`;
}

function createLandscapingIconSvg(label, palette) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96" role="img" aria-label="${escapeHtml(label)}">
  <rect width="96" height="96" rx="22" fill="${palette.dark}"/>
  <path d="M23 68c20-1 35-8 49-28" fill="none" stroke="${palette.pale}" stroke-width="7" stroke-linecap="round"/>
  <path d="M28 58c-1-20 13-34 34-34 3 20-8 37-29 40-3 0-5-2-5-6Z" fill="${palette.bright}"/>
  <path d="M33 57c8-10 18-18 29-25" fill="none" stroke="${palette.dark}" stroke-width="4" stroke-linecap="round" opacity=".45"/>
  <path d="M21 74h54" stroke="${palette.accent}" stroke-width="6" stroke-linecap="round"/>
  <path d="M25 42h13M21 51h14M58 70h17" stroke="${palette.pale}" stroke-width="5" stroke-linecap="round" opacity=".82"/>
</svg>
`;
}


module.exports={prepareGeneratedAssets,requirePreparedAssetManifest,recordAssetPreparation,hashApprovedAssetSet,readSeededAssetInventory};
