<?php
/* Template Name: Seasonal bake collection */
get_header(); ?>
<main id="primary">
<?php hearth_honey_intro( 'THE SEASONAL COLLECTION', 'A little of the season, baked in.', 'An imagined collection of rotating bakes. The photographs below are illustrative stock, not actual Hearth & Honey products.' ); ?>
<section class="container collection-grid inner-section"><figure><?php hearth_honey_photo( 'hero', 'collection-photo', true ); ?><figcaption>Loaves on the rack · Intrepid / Unsplash · Illustrative stock.</figcaption></figure><div class="collection-copy"><p class="eyebrow">AUTUMN / EARTHY & GOLDEN</p><h2>Roasted squash<br>&amp; rosemary.</h2><p>Soft roasted squash folded into a country dough, finished with rosemary and a little olive oil. An imagined October special for soup nights and thick slices of toast.</p><p><strong>Sample price: $10</strong> · Contains wheat.</p><?php hearth_honey_link( '/services/', 'Browse the daily menu ↗', 'text-link' ); ?></div><div class="collection-copy"><p class="eyebrow">WINTER / SOMETHING TO SHARE</p><h2>Walnut, honey<br>&amp; a warm kitchen.</h2><p>A gently sweet loaf with toasted walnuts and a dark, fragrant crust. Our winter menu idea pairs it with sharp cheese, a bowl of pears and good company.</p><p><strong>Sample price: $11</strong> · Contains wheat and walnuts.</p><?php hearth_honey_link( '/contact/#inquiry', 'Ask about seasonal bakes ↗', 'text-link' ); ?></div><figure><?php hearth_honey_photo( 'detail', 'collection-photo' ); ?><figcaption>Bread in a basket · Eric Prouzet / Unsplash · Illustrative stock.</figcaption></figure></section>
<section class="container season-notes"><article><p class="eyebrow">SPRING</p><h3>Lemon &amp; honey buns</h3><p>A bright lemon glaze over soft swirls. Sample price $5; contains wheat, milk and egg.</p></article><article><p class="eyebrow">SUMMER</p><h3>Tomato garden focaccia</h3><p>Ripe tomatoes, basil and olive oil. Sample price $7 per slice; contains wheat.</p></article></section>
<?php get_template_part( 'template-parts/content', 'cta-banner' ); ?>
</main><?php get_footer(); ?>
