<?php
/* Template Name: Bread journal */
get_header(); ?>
<main id="primary">
<?php hearth_honey_intro( 'NOTES FROM THE BAKERY', 'A few crumbs of wisdom.', 'Bread care, breakfast ideas and the pleasure of doing something slowly.' ); ?>
<div class="container journal-layout inner-section"><aside><figure><?php hearth_honey_photo( 'detail', 'arch-photo', true ); ?><figcaption>A basket of inspiration. Illustrative stock.</figcaption></figure><p class="eyebrow">THE KITCHEN NOTEBOOK</p><nav aria-label="Journal notes"><a href="#keep-a-loaf">Keeping your loaf happy</a><a href="#freeze-bread">A little bread for later</a><a href="#morning-toast">The three-minute toast ritual</a></nav></aside><div>
<article class="journal-entry" id="keep-a-loaf"><p class="eyebrow">BREAD CARE / 3 MIN READ</p><h2>Keeping your loaf happy.</h2><p>On the first day, keep a cut loaf cut-side down on a board. Its own crust helps protect the soft middle. For the next day or two, a bread bag or loosely wrapped clean tea towel keeps it close at hand.</p><p>Skip the refrigerator: bread tends to stale faster there. Once the crust begins to soften, a few minutes in a warm oven brings back some of that first-day character. Warm only what you plan to eat.</p><p>See any mold? Discard the whole loaf. A good breakfast is also a sensible one.</p></article>
<article class="journal-entry" id="freeze-bread"><p class="eyebrow">LESS WASTE / 2 MIN READ</p><h2>A little bread for later.</h2><p>Slice the portion you won’t finish while it is still fresh. Let it cool completely, then freeze the slices in an airtight freezer bag with small pieces of baking paper between them.</p><p>Toast straight from frozen, adding a little extra time. For best flavor, enjoy within a month. Your future self now has excellent toast waiting.</p></article>
<article class="journal-entry" id="morning-toast"><p class="eyebrow">MORNING RITUALS / 2 MIN READ</p><h2>The three-minute toast ritual.</h2><p>Cut a generous slice. Toast until the edges are crisp and the middle is still soft. Spread butter while it is warm, then add honey and a tiny pinch of flaky salt.</p><p>For a savory morning, try crushed ripe tomato, olive oil and black pepper. Put the phone down for the first few bites. Some small things deserve your full attention.</p><?php hearth_honey_link( '/services/', 'Pick your next loaf ↗', 'text-link' ); ?></article>
</div></div></main><?php get_footer(); ?>
