<?php
/* Template Name: Bake and coffee menu */
get_header(); ?>
<main id="primary">
<?php hearth_honey_intro( 'THE BAKE MENU', 'Follow your appetite.', 'A loaf for later. A bun for right now. Coffee for the bit in between. All prices are sample prices in USD.' ); ?>
<?php get_template_part( 'template-parts/content', 'all-services' ); ?>
<section class="container split inner-section" id="coffee"><div><p class="eyebrow">THE COFFEE COUNTER</p><h2>Find your usual.</h2><p>A small, considered coffee menu to keep your morning moving, or make it last a little longer. Dairy and oat milk available.</p><dl class="coffee-list"><div><dt>Espresso</dt><dd>$3</dd></div><div><dt>Batch brew</dt><dd>$3.50</dd></div><div><dt>Flat white</dt><dd>$4.50</dd></div><div><dt>Honey latte, hot or iced</dt><dd>$5.50</dd></div><div><dt>Loose-leaf tea</dt><dd>$3.50</dd></div></dl></div><figure><?php hearth_honey_photo( 'hero', 'arch-photo' ); ?><figcaption>Something good alongside your coffee. Illustrative stock.</figcaption></figure></section>
<section class="butter-band"><div class="container split"><div><p class="eyebrow">A BIGGER TABLE</p><h2>Good things<br>are for sharing.</h2><p>Weekend boxes are a lovely place to start. For a gathering, our sample catering menu offers sliced country loaves, rosemary focaccia and trays of honey buns for 8–30 guests.</p><p>Plan at least three days ahead. Final quantities, ingredients and availability would be agreed with the bakery before any real order.</p><?php hearth_honey_link( '/contact/#inquiry', 'Ask about catering ↗', 'button' ); ?></div><?php get_template_part( 'template-parts/content', 'single-service-highlight' ); ?></div></section>
<section class="container narrow inner-section"><h2>A few things to know.</h2><details><summary>Which allergens are in the bakes?</summary><p>All breads contain wheat. Seeded loaves also contain sesame. Honey buns contain wheat, milk and egg; honey butter contains milk. Everything shares a preparation space, so this sample menu cannot promise an allergen-free product.</p></details><details><summary>Can I reserve a loaf?</summary><p>This sample site does not take reservations. At a real bakery, check availability directly before making a special trip. Fresh loaves are best collected early.</p></details><details><summary>Is sourdough gluten-free?</summary><p>No. Our sample sourdough uses wheat flour and contains gluten. Slow fermentation does not make it gluten-free.</p></details></section>
</main><?php get_footer(); ?>
