<?php
/** Template Name: Route Field Notes */
get_header(); ?>
<main id="primary" tabindex="-1">
<?php rr_page_intro( 'FIELD NOTES / SAMPLE ITINERARIES', 'A few lines worth following.', 'Imagined days outside, collected like pages in a walking notebook. These are route concepts, not directions or records of completed trips.' ); ?>
<section class="container field-note section" id="river"><div><p class="eyebrow">NOTE 001 / EASY / 6 KM / 3 HOURS</p><h2>River & woodland loop</h2><p class="lead">Start with the sound of water. Finish with mud on your boots and a little more room in your head.</p><p>A sample morning begins on an established riverside path, rises gently into woodland and returns by the same valley. Allow time for two short rests and a longer stop before the return.</p><h3>In the notebook</h3><p>Mostly even terrain in this concept, with some roots and damp sections. A real outing would need checks for river levels, path access and suitable facilities.</p><?php rr_link( '/contact/', 'Talk about a gentle walk ↗', 'text-link' ); ?></div><figure><?php rr_photo(); ?><figcaption>Landscape study — illustrative stock, not this route.</figcaption></figure></section>
<section class="container field-note section" id="ridge"><div><p class="eyebrow">NOTE 002 / CHALLENGING / 14 KM / 7 HOURS</p><h2>The long ridge</h2><p class="lead">A day measured in changing perspectives.</p><p>Build in time for a steady ascent, a sheltered lunch and an unhurried descent. The interesting part is choosing the right pace and noticing how the valley changes as you climb.</p><h3>In the notebook</h3><p>Previous hill experience, appropriate kit and a willingness to change the plan are central to this concept. It is a walking itinerary, not a climbing or mountaineering offer.</p><?php rr_link( '/services/featured/', 'Read the full-day itinerary ↗', 'text-link' ); ?></div><aside class="field-jot"><?php rr_mark( 2 ); ?><p>“The best line on the map is the one that makes sense on the day.”</p><span class="mono">RIDGE & RIVER / PLANNING NOTE</span></aside></section>
<?php rr_next_step(); ?>
</main><?php get_footer(); ?>
